version: "3.9"

x-project-name: &project_name search-engine

x-config:
  base_app: &base
    image: *project_name
    build:
      context: .
    env_file:
      - .env.compose
    depends_on:
      - postgres
      - redis

  base-with-volume: &base_with_volume
    <<: *base
    volumes:
      - ./backend:/backend


services:
  app:
    <<: *base_with_volume
    command: [ "sh", "-e", "/backend/bin/run-app.sh" ]
    ports:
      - "8000:8000"

  dramatiq:
    <<: *base_with_volume
    command: [ "sh", "-e", "/backend/bin/run-dramatiq.sh" ]
    ports:
      - "9192:9191"

  scheduler:
    <<: *base_with_volume
    command: [ "sh", "-e", "/backend/bin/run-scheduler.sh" ]

  tests-in-ci:
    <<: *base
    container_name: tests-in-ci
    command: [ "sh", "-e", "/backend/bin/run-tests.sh" ]
    environment:
      DJANGO_SETTINGS_MODULE: app.settings.test

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5435:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6376:6379"

  redis-ui:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redis:/db
    depends_on:
      - redis

volumes:
  postgres:
  redis:
