# Generated by Django 3.2.16 on 2022-10-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="status",
            field=models.CharField(
                choices=[("Запущен", "Запущен"), ("Готово", "Готово"), ("Ошибка", "Ошибка")],
                default="Запущен",
                editable=False,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="urls",
            field=models.ManyToManyField(editable=False, to="core.Url"),
        ),
    ]
