# Generated by Django 3.2.16 on 2022-11-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20221031_1431"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={"verbose_name": "Связь", "verbose_name_plural": "Связи"},
        ),
        migrations.AlterModelOptions(
            name="linkword",
            options={"verbose_name": "Связь <-> Слово", "verbose_name_plural": "Связи <-> Слова"},
        ),
        migrations.AlterModelOptions(
            name="pagerank",
            options={"verbose_name": "Ранг страницы", "verbose_name_plural": "Ранги страниц"},
        ),
        migrations.AlterModelOptions(
            name="run",
            options={"verbose_name": "Запуск", "verbose_name_plural": "Запуски"},
        ),
        migrations.AlterModelOptions(
            name="url",
            options={"verbose_name": "Ссылка", "verbose_name_plural": "Ссылки"},
        ),
        migrations.AlterModelOptions(
            name="urlword",
            options={"verbose_name": "Ссылка <-> Слово", "verbose_name_plural": "Ссылки <-> Слова"},
        ),
        migrations.AlterModelOptions(
            name="word",
            options={"verbose_name": "Слово", "verbose_name_plural": "Слова"},
        ),
    ]
