# Generated by Django 3.2.16 on 2022-11-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20221101_1520"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="urlword",
            unique_together={("url", "word", "location")},
        ),
    ]
