# Generated by Django 3.2.16 on 2022-11-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_urlword_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="is_crawled",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
