# Generated by Django 3.2.16 on 2022-11-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_url_is_crawled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="is_filtered",
        ),
    ]
