# Generated by Django 3.2.16 on 2022-11-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_word_is_filtered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="depth",
            field=models.IntegerField(
                default=1, verbose_name="Глубина обхода (0 - только страницу, 1 - +вложенные и т.д.)"
            ),
        ),
    ]
