# Generated by Django 3.2.16 on 2022-11-07 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_run_depth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagerank",
            name="url",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ranks", to="core.url"),
        ),
    ]
