# Generated by Django 3.2.13 on 2022-09-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                ("key", models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name="Ключ")),
                ("value", models.TextField(verbose_name="Значение")),
                ("description", models.TextField(null=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Параметр конфигурации",
                "verbose_name_plural": "Конфигурация приложения",
                "db_table": "config",
            },
        ),
    ]
